spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/Employee
    username: postgres
    password: andrei1234
  
  jpa:
    # defer-datasource-initialization: true
    # show-sql: true
    # generate-ddl: true
    hibernate:
      # # naming:
        # # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      ddl-auto: update

management:
  endpoints:
    jmx:
      exposure:
        include: '*'